### ISSUE TITLE
Issue at line 42 of collect_to_frame.do

### ISSUE THREAD

**Issue by tpcopeland** [daniel-alves-fernandes/collect-to-frame#1]
Apologies in advance for being unfamiliar with GitHub etiquette for the format of this issue report. 

I was getting an error that mentioned "'unicodeescape' codec can't decode bytes in position 2-3."

I resolved the issue by adding an 'r' in front of "`stjson_file'" on line 42 of the ado file.

When line 42 is specified as below, the command works without reporting an error:
python: collect_to_frame(r"`stjson_file'","`labels'")

Thank you for developing this useful package!

**Comment by daniel-alves-fernandes** [comment]
Thank you for reporting this issue. It's fixed!
